meta_product_name: "Bookflow"
meta_title: "Bookflow - Share and Discover Books!"
meta_description: "Mobile application designed to help book lovers find new books and track their reading progress"
meta_image: "cover.png" # should exist in `app/assets/images/`
